# Generated by Django 5.2.7 on 2025-10-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_resume_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('mandatory_skills', models.JSONField()),
                ('optional_skills', models.JSONField(blank=True, default=list)),
                ('interviewer_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_slots', models.JSONField()),
                ('interview_instructions', models.TextField(blank=True)),
                ('match_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending Review', max_length=50)),
                ('resume_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='resume_app.resume')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='resume_app.jobposition')),
            ],
        ),
    ]
