# Generated by Django 5.2.7 on 2025-10-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_jobposition_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Unknown', max_length=255)),
                ('domain', models.CharField(default='Unknown', max_length=255)),
                ('exp_from', models.IntegerField(default=0)),
                ('exp_to', models.IntegerField(default=0)),
                ('job_description_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('mandatory_skills', models.JSONField(default=list)),
                ('optional_skills', models.JSONField(default=list)),
                ('interview_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_data',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='availability_slots',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.AddField(
            model_name='candidate',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='domain',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='candidate_jd/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mandatory_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='optional_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.position'),
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
